export const config = { api: { bodyParser: true } };

const DEMO_USERS = [
  {
    "id": 1,
    "name": "מאיה לוי",
    "email": "maya@collabo.io",
    "password": "Maya1234",
    "role": "creator",
    "cats": "אוכל, לייפסטייל, UGC",
    "city": "תל אביב",
    "status": "active",
    "joined": "26/05/2025",
    "color": "rgba(0,207,255,0.15)",
    "textColor": "#00cfff"
  },
  {
    "id": 2,
    "name": "Urban Eats TLV",
    "email": "urban@collabo.io",
    "password": "Urban1234",
    "role": "business",
    "cats": "מסעדה ואוכל",
    "city": "תל אביב",
    "status": "active",
    "joined": "25/05/2025",
    "color": "rgba(255,215,0,0.15)",
    "textColor": "#ffd700"
  },
  {
    "id": 3,
    "name": "נועם כהן",
    "email": "noam@collabo.io",
    "password": "Noam1234",
    "role": "creator",
    "cats": "כושר, ספורט",
    "city": "הרצליה",
    "status": "active",
    "joined": "24/05/2025",
    "color": "rgba(0,229,160,0.15)",
    "textColor": "#00e5a0"
  },
  {
    "id": 4,
    "name": "Café Roma",
    "email": "roma@collabo.io",
    "password": "Roma1234",
    "role": "business",
    "cats": "קפה",
    "city": "רמת גן",
    "status": "active",
    "joined": "23/05/2025",
    "color": "rgba(255,77,77,0.15)",
    "textColor": "#ff4d4d"
  },
  {
    "id": 5,
    "name": "שירה אביב",
    "email": "shira@collabo.io",
    "password": "Shira1234",
    "role": "creator",
    "cats": "אופנה, יופי",
    "city": "תל אביב",
    "status": "active",
    "joined": "22/05/2025",
    "color": "rgba(245,166,35,0.15)",
    "textColor": "#f5a623"
  },
  {
    "id": 10,
    "name": "נועה כהן",
    "email": "נועהכהן@collabo.io",
    "password": "נועה1234",
    "role": "creator",
    "cats": "אוכל, בישול, מתכונים",
    "city": "תל אביב",
    "handle": "@noakitchen",
    "followers": "84K",
    "engagement": "6.2%",
    "price": "₪800-3,500",
    "bio": "שפית אוכל ביתי 🍳",
    "status": "active",
    "joined": "27/005/2025",
    "color": "rgba(0,207,255,0.15)",
    "textColor": "#00cfff",
    "emoji": "📸",
    "verified": true
  },
  {
    "id": 11,
    "name": "יואב לוי",
    "email": "יואבלוי@collabo.io",
    "password": "יואב1234",
    "role": "creator",
    "cats": "אוכל, מסעדות",
    "city": "תל אביב",
    "handle": "@yoavfood",
    "followers": "120K",
    "engagement": "5.8%",
    "price": "₪1,200-5,000",
    "bio": "מבקר מסעדות ✨",
    "status": "active",
    "joined": "19/001/2025",
    "color": "rgba(255,215,0,0.15)",
    "textColor": "#ffd700",
    "emoji": "🎬",
    "verified": true
  },
  {
    "id": 12,
    "name": "מיכל דוד",
    "email": "מיכלדוד@collabo.io",
    "password": "מיכל1234",
    "role": "creator",
    "cats": "אוכל, טבעוני",
    "city": "תל אביב",
    "handle": "@michalvegan",
    "followers": "67K",
    "engagement": "7.1%",
    "price": "₪700-2,800",
    "bio": "חיים טבעוניים 🌱",
    "status": "active",
    "joined": "08/005/2025",
    "color": "rgba(0,229,160,0.15)",
    "textColor": "#00e5a0",
    "emoji": "✨",
    "verified": true
  },
  {
    "id": 13,
    "name": "אורי ברק",
    "email": "אוריברק@collabo.io",
    "password": "אורי1234",
    "role": "creator",
    "cats": "אוכל, גריל",
    "city": "ראשון לציון",
    "handle": "@uribbq",
    "followers": "95K",
    "engagement": "5.4%",
    "price": "₪900-3,800",
    "bio": "מלך הגריל 🔥",
    "status": "active",
    "joined": "26/004/2025",
    "color": "rgba(255,77,77,0.15)",
    "textColor": "#ff4d4d",
    "emoji": "🌟",
    "verified": true
  },
  {
    "id": 14,
    "name": "שני אברהם",
    "email": "שניאברהם@collabo.io",
    "password": "שני1234",
    "role": "creator",
    "cats": "אוכל, אפייה",
    "city": "חיפה",
    "handle": "@shanibakes",
    "followers": "52K",
    "engagement": "8.3%",
    "price": "₪600-2,200",
    "bio": "אופה חובבת 🎂",
    "status": "active",
    "joined": "13/005/2025",
    "color": "rgba(245,166,35,0.15)",
    "textColor": "#f5a623",
    "emoji": "💫",
    "verified": false
  },
  {
    "id": 15,
    "name": "דניאל מזרחי",
    "email": "דניאלמזרחי@collabo.io",
    "password": "דניאל1234",
    "role": "creator",
    "cats": "לייפסטייל, נסיעות",
    "city": "תל אביב",
    "handle": "@daniellife",
    "followers": "210K",
    "engagement": "4.9%",
    "price": "₪2,000-8,000",
    "bio": "חיים יפים 📸",
    "status": "active",
    "joined": "07/003/2025",
    "color": "rgba(168,85,247,0.15)",
    "textColor": "#a855f7",
    "emoji": "🎨",
    "verified": true
  },
  {
    "id": 16,
    "name": "רוני שפירא",
    "email": "רונישפירא@collabo.io",
    "password": "רוני1234",
    "role": "creator",
    "cats": "לייפסטייל, בית",
    "city": "הרצליה",
    "handle": "@ronishapira",
    "followers": "78K",
    "engagement": "6.7%",
    "price": "₪800-3,200",
    "bio": "עיצוב בית 🏠",
    "status": "active",
    "joined": "05/001/2025",
    "color": "rgba(236,72,153,0.15)",
    "textColor": "#ec4899",
    "emoji": "🎵",
    "verified": true
  },
  {
    "id": 17,
    "name": "גלית עוז",
    "email": "גליתעוז@collabo.io",
    "password": "גלית1234",
    "role": "creator",
    "cats": "לייפסטייל, אמהות",
    "city": "רמת גן",
    "handle": "@galitoz",
    "followers": "143K",
    "engagement": "5.2%",
    "price": "₪1,400-5,500",
    "bio": "אמא, אישה, יזמית 💪",
    "status": "active",
    "joined": "03/002/2025",
    "color": "rgba(0,207,255,0.15)",
    "textColor": "#00cfff",
    "emoji": "🏃",
    "verified": true
  },
  {
    "id": 18,
    "name": "עמית כץ",
    "email": "עמיתכץ@collabo.io",
    "password": "עמית1234",
    "role": "creator",
    "cats": "לייפסטייל, גברים",
    "city": "תל אביב",
    "handle": "@amitlife",
    "followers": "89K",
    "engagement": "5.9%",
    "price": "₪900-3,600",
    "bio": "לייפסטייל גברי 🕶️",
    "status": "active",
    "joined": "27/004/2025",
    "color": "rgba(255,215,0,0.15)",
    "textColor": "#ffd700",
    "emoji": "🧘",
    "verified": true
  },
  {
    "id": 19,
    "name": "יעל גרין",
    "email": "יעלגרין@collabo.io",
    "password": "יעל1234",
    "role": "creator",
    "cats": "לייפסטייל, קיימות",
    "city": "תל אביב",
    "handle": "@yaelgreen",
    "followers": "61K",
    "engagement": "7.4%",
    "price": "₪700-2,600",
    "bio": "חיים ירוקים 🌿",
    "status": "active",
    "joined": "10/005/2025",
    "color": "rgba(0,229,160,0.15)",
    "textColor": "#00e5a0",
    "emoji": "🌿",
    "verified": true
  },
  {
    "id": 20,
    "name": "שירה בן דוד",
    "email": "שירהבןדוד@collabo.io",
    "password": "שירה1234",
    "role": "creator",
    "cats": "אופנה, סטייל",
    "city": "תל אביב",
    "handle": "@shirafashion",
    "followers": "185K",
    "engagement": "5.1%",
    "price": "₪1,800-7,000",
    "bio": "סטייל ישראלי 👗",
    "status": "active",
    "joined": "25/001/2025",
    "color": "rgba(255,77,77,0.15)",
    "textColor": "#ff4d4d",
    "emoji": "💄",
    "verified": false
  },
  {
    "id": 21,
    "name": "רז אלון",
    "email": "רזאלון@collabo.io",
    "password": "רז1234",
    "role": "creator",
    "cats": "אופנה, גברים",
    "city": "תל אביב",
    "handle": "@razstyle",
    "followers": "97K",
    "engagement": "5.6%",
    "price": "₪1,000-4,200",
    "bio": "אופנת גברים 🎩",
    "status": "active",
    "joined": "24/002/2025",
    "color": "rgba(245,166,35,0.15)",
    "textColor": "#f5a623",
    "emoji": "👗",
    "verified": true
  },
  {
    "id": 22,
    "name": "נטע רוזן",
    "email": "נטערוזן@collabo.io",
    "password": "נטע1234",
    "role": "creator",
    "cats": "אופנה, יוקרה",
    "city": "הרצליה",
    "handle": "@netafashion",
    "followers": "230K",
    "engagement": "4.7%",
    "price": "₪2,500-9,000",
    "bio": "לוקסוס נגיש 💎",
    "status": "active",
    "joined": "26/005/2025",
    "color": "rgba(168,85,247,0.15)",
    "textColor": "#a855f7",
    "emoji": "🍕",
    "verified": true
  },
  {
    "id": 23,
    "name": "אלה שמש",
    "email": "אלהשמש@collabo.io",
    "password": "אלה1234",
    "role": "creator",
    "cats": "אופנה, טרנדים",
    "city": "תל אביב",
    "handle": "@ellastyle",
    "followers": "74K",
    "engagement": "6.8%",
    "price": "₪800-3,000",
    "bio": "טרנדים עכשיו 🔥",
    "status": "active",
    "joined": "01/001/2025",
    "color": "rgba(236,72,153,0.15)",
    "textColor": "#ec4899",
    "emoji": "☕",
    "verified": true
  },
  {
    "id": 24,
    "name": "תומר נגל",
    "email": "תומרנגל@collabo.io",
    "password": "תומר1234",
    "role": "creator",
    "cats": "אופנה, נעליים",
    "city": "תל אביב",
    "handle": "@tomernagel",
    "followers": "112K",
    "engagement": "5.5%",
    "price": "₪1,100-4,500",
    "bio": "סניקרס 👟",
    "status": "active",
    "joined": "02/005/2025",
    "color": "rgba(0,207,255,0.15)",
    "textColor": "#00cfff",
    "emoji": "✈️",
    "verified": true
  },
  {
    "id": 25,
    "name": "רם שלום",
    "email": "רםשלום@collabo.io",
    "password": "רם1234",
    "role": "creator",
    "cats": "כושר, תזונה",
    "city": "תל אביב",
    "handle": "@ramfitness",
    "followers": "156K",
    "engagement": "6.3%",
    "price": "₪1,500-6,000",
    "bio": "מאמן כושר 💪",
    "status": "active",
    "joined": "08/002/2025",
    "color": "rgba(255,215,0,0.15)",
    "textColor": "#ffd700",
    "emoji": "💪",
    "verified": false
  },
  {
    "id": 26,
    "name": "לירון כהן",
    "email": "לירוןכהן@collabo.io",
    "password": "לירון1234",
    "role": "creator",
    "cats": "כושר, יוגה",
    "city": "תל אביב",
    "handle": "@lironyoga",
    "followers": "88K",
    "engagement": "7.2%",
    "price": "₪900-3,500",
    "bio": "יוגה כדרך חיים 🧘",
    "status": "active",
    "joined": "21/001/2025",
    "color": "rgba(0,229,160,0.15)",
    "textColor": "#00e5a0",
    "emoji": "🎮",
    "verified": true
  },
  {
    "id": 27,
    "name": "אבי גל",
    "email": "אביגל@collabo.io",
    "password": "אבי1234",
    "role": "creator",
    "cats": "כושר, ריצה",
    "city": "ירושלים",
    "handle": "@avigal_sport",
    "followers": "64K",
    "engagement": "6.9%",
    "price": "₪700-2,800",
    "bio": "רץ מרתון 🏃",
    "status": "active",
    "joined": "15/004/2025",
    "color": "rgba(255,77,77,0.15)",
    "textColor": "#ff4d4d",
    "emoji": "📚",
    "verified": false
  },
  {
    "id": 28,
    "name": "נדב ברון",
    "email": "נדבברון@collabo.io",
    "password": "נדב1234",
    "role": "creator",
    "cats": "כושר, קרוספיט",
    "city": "תל אביב",
    "handle": "@nadavfit",
    "followers": "103K",
    "engagement": "5.8%",
    "price": "₪1,000-4,200",
    "bio": "קרוספיט 🏋️",
    "status": "active",
    "joined": "01/002/2025",
    "color": "rgba(245,166,35,0.15)",
    "textColor": "#f5a623",
    "emoji": "🔬",
    "verified": true
  },
  {
    "id": 29,
    "name": "מור לוי",
    "email": "מורלוי@collabo.io",
    "password": "מור1234",
    "role": "creator",
    "cats": "כושר, בריאות",
    "city": "נתניה",
    "handle": "@morfitlife",
    "followers": "71K",
    "engagement": "7.5%",
    "price": "₪750-2,900",
    "bio": "בריאות = השקעה 🌟",
    "status": "active",
    "joined": "06/004/2025",
    "color": "rgba(168,85,247,0.15)",
    "textColor": "#a855f7",
    "emoji": "🚀",
    "verified": true
  },
  {
    "id": 30,
    "name": "איתי מור",
    "email": "איתימור@collabo.io",
    "password": "איתי1234",
    "role": "creator",
    "cats": "טיולים, הרפתקאות",
    "city": "תל אביב",
    "handle": "@itaytravel",
    "followers": "198K",
    "engagement": "5.3%",
    "price": "₪2,000-8,500",
    "bio": "60 מדינות ✈️",
    "status": "active",
    "joined": "12/004/2025",
    "color": "rgba(236,72,153,0.15)",
    "textColor": "#ec4899",
    "emoji": "📸",
    "verified": false
  },
  {
    "id": 31,
    "name": "מיה פרץ",
    "email": "מיהפרץ@collabo.io",
    "password": "מיה1234",
    "role": "creator",
    "cats": "טיולים, אסיה",
    "city": "תל אביב",
    "handle": "@miyaexplores",
    "followers": "134K",
    "engagement": "5.7%",
    "price": "₪1,300-5,500",
    "bio": "מגלה עולם 🗺️",
    "status": "active",
    "joined": "02/002/2025",
    "color": "rgba(0,207,255,0.15)",
    "textColor": "#00cfff",
    "emoji": "🎬",
    "verified": true
  },
  {
    "id": 32,
    "name": "גיל אדר",
    "email": "גילאדר@collabo.io",
    "password": "גיל1234",
    "role": "creator",
    "cats": "טיולים, טבע",
    "city": "חיפה",
    "handle": "@giladventure",
    "followers": "76K",
    "engagement": "6.4%",
    "price": "₪800-3,200",
    "bio": "טבע ושקט ⛺",
    "status": "active",
    "joined": "06/004/2025",
    "color": "rgba(255,215,0,0.15)",
    "textColor": "#ffd700",
    "emoji": "✨",
    "verified": true
  },
  {
    "id": 33,
    "name": "טל שגיא",
    "email": "טלשגיא@collabo.io",
    "password": "טל1234",
    "role": "creator",
    "cats": "טיולים, תקציב",
    "city": "באר שבע",
    "handle": "@taltrip",
    "followers": "58K",
    "engagement": "7.8%",
    "price": "₪600-2,400",
    "bio": "לטייל בזול 💰",
    "status": "active",
    "joined": "23/005/2025",
    "color": "rgba(0,229,160,0.15)",
    "textColor": "#00e5a0",
    "emoji": "🌟",
    "verified": true
  },
  {
    "id": 34,
    "name": "אנה סמית",
    "email": "אנהסמית@collabo.io",
    "password": "אנה1234",
    "role": "creator",
    "cats": "יופי, מייקאפ",
    "city": "תל אביב",
    "handle": "@anabeauty",
    "followers": "167K",
    "engagement": "5.5%",
    "price": "₪1,600-6,500",
    "bio": "מייקאפ ארטיסט 💄",
    "status": "active",
    "joined": "01/005/2025",
    "color": "rgba(255,77,77,0.15)",
    "textColor": "#ff4d4d",
    "emoji": "💫",
    "verified": true
  },
  {
    "id": 35,
    "name": "הדר לוי",
    "email": "הדרלוי@collabo.io",
    "password": "הדר1234",
    "role": "creator",
    "cats": "יופי, עור",
    "city": "תל אביב",
    "handle": "@hadarskinn",
    "followers": "92K",
    "engagement": "6.1%",
    "price": "₪950-3,800",
    "bio": "טיפוח עור 🧴",
    "status": "active",
    "joined": "16/001/2025",
    "color": "rgba(245,166,35,0.15)",
    "textColor": "#f5a623",
    "emoji": "🎨",
    "verified": false
  },
  {
    "id": 36,
    "name": "ספיר גולן",
    "email": "ספירגולן@collabo.io",
    "password": "ספיר1234",
    "role": "creator",
    "cats": "יופי, ציפורניים",
    "city": "רמת גן",
    "handle": "@sapirnails",
    "followers": "83K",
    "engagement": "7.6%",
    "price": "₪850-3,200",
    "bio": "ציפורניים כאמנות 💅",
    "status": "active",
    "joined": "09/001/2025",
    "color": "rgba(168,85,247,0.15)",
    "textColor": "#a855f7",
    "emoji": "🎵",
    "verified": true
  },
  {
    "id": 37,
    "name": "אלינה בר",
    "email": "אלינהבר@collabo.io",
    "password": "אלינה1234",
    "role": "creator",
    "cats": "יופי, שיער",
    "city": "תל אביב",
    "handle": "@alinahair",
    "followers": "119K",
    "engagement": "5.9%",
    "price": "₪1,200-4,800",
    "bio": "שיער מושלם 💇",
    "status": "active",
    "joined": "02/001/2025",
    "color": "rgba(236,72,153,0.15)",
    "textColor": "#ec4899",
    "emoji": "🏃",
    "verified": false
  },
  {
    "id": 38,
    "name": "רחל מוסרי",
    "email": "רחלמוסרי@collabo.io",
    "password": "רחל1234",
    "role": "creator",
    "cats": "יופי, טבעי",
    "city": "ירושלים",
    "handle": "@rachelbeauty",
    "followers": "55K",
    "engagement": "8.1%",
    "price": "₪600-2,300",
    "bio": "יופי טבעי 🌸",
    "status": "active",
    "joined": "15/005/2025",
    "color": "rgba(0,207,255,0.15)",
    "textColor": "#00cfff",
    "emoji": "🧘",
    "verified": false
  },
  {
    "id": 39,
    "name": "אלון ביטון",
    "email": "אלוןביטון@collabo.io",
    "password": "אלון1234",
    "role": "creator",
    "cats": "טכנולוגיה, AI",
    "city": "תל אביב",
    "handle": "@alontech",
    "followers": "145K",
    "engagement": "5.2%",
    "price": "₪1,400-5,800",
    "bio": "טכנולוגיה לכולם 📱",
    "status": "active",
    "joined": "15/004/2025",
    "color": "rgba(255,215,0,0.15)",
    "textColor": "#ffd700",
    "emoji": "🌿",
    "verified": true
  },
  {
    "id": 40,
    "name": "יונתן סגל",
    "email": "יונתןסגל@collabo.io",
    "password": "יונתן1234",
    "role": "creator",
    "cats": "טכנולוגיה, סייבר",
    "city": "תל אביב",
    "handle": "@yonisegal",
    "followers": "87K",
    "engagement": "5.7%",
    "price": "₪900-3,600",
    "bio": "אבטחת מידע 🔒",
    "status": "active",
    "joined": "09/003/2025",
    "color": "rgba(0,229,160,0.15)",
    "textColor": "#00e5a0",
    "emoji": "💄",
    "verified": true
  },
  {
    "id": 41,
    "name": "רות שרון",
    "email": "רותשרון@collabo.io",
    "password": "רות1234",
    "role": "creator",
    "cats": "טכנולוגיה, קריירה",
    "city": "תל אביב",
    "handle": "@ruthtech",
    "followers": "73K",
    "engagement": "6.5%",
    "price": "₪750-3,000",
    "bio": "הייטק וקריירה 💻",
    "status": "active",
    "joined": "15/003/2025",
    "color": "rgba(255,77,77,0.15)",
    "textColor": "#ff4d4d",
    "emoji": "👗",
    "verified": true
  },
  {
    "id": 42,
    "name": "בן אורן",
    "email": "בןאורן@collabo.io",
    "password": "בן1234",
    "role": "creator",
    "cats": "UGC, מוצרים",
    "city": "תל אביב",
    "handle": "@benugc",
    "followers": "38K",
    "engagement": "9.2%",
    "price": "₪400-1,800",
    "bio": "UGC creator 📦",
    "status": "active",
    "joined": "17/002/2025",
    "color": "rgba(245,166,35,0.15)",
    "textColor": "#f5a623",
    "emoji": "🍕",
    "verified": true
  },
  {
    "id": 43,
    "name": "מאיה זיו",
    "email": "מאיהזיו@collabo.io",
    "password": "מאיה1234",
    "role": "creator",
    "cats": "UGC, בית",
    "city": "פתח תקווה",
    "handle": "@mayaugc",
    "followers": "29K",
    "engagement": "10.1%",
    "price": "₪350-1,500",
    "bio": "UGC מהבית 🏠",
    "status": "active",
    "joined": "24/003/2025",
    "color": "rgba(168,85,247,0.15)",
    "textColor": "#a855f7",
    "emoji": "☕",
    "verified": true
  },
  {
    "id": 44,
    "name": "ליאור גל",
    "email": "ליאורגל@collabo.io",
    "password": "ליאור1234",
    "role": "creator",
    "cats": "UGC, מזון",
    "city": "חיפה",
    "handle": "@liaorugc",
    "followers": "34K",
    "engagement": "9.8%",
    "price": "₪380-1,600",
    "bio": "UGC מזון 🍕",
    "status": "active",
    "joined": "01/002/2025",
    "color": "rgba(236,72,153,0.15)",
    "textColor": "#ec4899",
    "emoji": "✈️",
    "verified": false
  },
  {
    "id": 45,
    "name": "אריאל כץ",
    "email": "אריאלכץ@collabo.io",
    "password": "אריאל1234",
    "role": "creator",
    "cats": "פיננסים, השקעות",
    "city": "תל אביב",
    "handle": "@arielfinance",
    "followers": "178K",
    "engagement": "5.4%",
    "price": "₪1,700-7,000",
    "bio": "כסף זה לא טאבו 💸",
    "status": "active",
    "joined": "25/004/2025",
    "color": "rgba(0,207,255,0.15)",
    "textColor": "#00cfff",
    "emoji": "💪",
    "verified": true
  },
  {
    "id": 46,
    "name": "נועם זוהר",
    "email": "נועםזוהר@collabo.io",
    "password": "נועם1234",
    "role": "creator",
    "cats": "פיננסים, נדלן",
    "city": "הרצליה",
    "handle": "@noamzohar",
    "followers": "124K",
    "engagement": "5.1%",
    "price": "₪1,200-5,000",
    "bio": "בונה עושר 🏦",
    "status": "active",
    "joined": "24/003/2025",
    "color": "rgba(255,215,0,0.15)",
    "textColor": "#ffd700",
    "emoji": "🎮",
    "verified": false
  },
  {
    "id": 47,
    "name": "ליאב שחר",
    "email": "ליאבשחר@collabo.io",
    "password": "ליאב1234",
    "role": "creator",
    "cats": "וידאו, קולנוע",
    "city": "תל אביב",
    "handle": "@liavfilm",
    "followers": "93K",
    "engagement": "6.3%",
    "price": "₪950-4,000",
    "bio": "מספר סיפורים 🎬",
    "status": "active",
    "joined": "03/001/2025",
    "color": "rgba(0,229,160,0.15)",
    "textColor": "#00e5a0",
    "emoji": "📚",
    "verified": true
  },
  {
    "id": 48,
    "name": "הילה אמדי",
    "email": "הילהאמדי@collabo.io",
    "password": "הילה1234",
    "role": "creator",
    "cats": "וידאו, ריילס",
    "city": "תל אביב",
    "handle": "@hilafilm",
    "followers": "158K",
    "engagement": "5.6%",
    "price": "₪1,500-6,200",
    "bio": "ריילס שאנשים שומרים 🎥",
    "status": "active",
    "joined": "26/004/2025",
    "color": "rgba(255,77,77,0.15)",
    "textColor": "#ff4d4d",
    "emoji": "🔬",
    "verified": true
  },
  {
    "id": 49,
    "name": "טלי כהן",
    "email": "טליכהן@collabo.io",
    "password": "טלי1234",
    "role": "creator",
    "cats": "חיות מחמד, כלבים",
    "city": "תל אביב",
    "handle": "@talidogs",
    "followers": "112K",
    "engagement": "7.8%",
    "price": "₪1,100-4,300",
    "bio": "3 כלבים מדהימים 🐕",
    "status": "active",
    "joined": "12/005/2025",
    "color": "rgba(245,166,35,0.15)",
    "textColor": "#f5a623",
    "emoji": "🚀",
    "verified": false
  },
  {
    "id": 50,
    "name": "רועי עמר",
    "email": "רועיעמר@collabo.io",
    "password": "רועי1234",
    "role": "creator",
    "cats": "חיות מחמד, חתולים",
    "city": "ירושלים",
    "handle": "@royicats",
    "followers": "78K",
    "engagement": "8.4%",
    "price": "₪800-3,100",
    "bio": "חתולים הם החיים 🐱",
    "status": "active",
    "joined": "02/002/2025",
    "color": "rgba(168,85,247,0.15)",
    "textColor": "#a855f7",
    "emoji": "📸",
    "verified": true
  },
  {
    "id": 51,
    "name": "עדן הרוש",
    "email": "עדןהרוש@collabo.io",
    "password": "עדן1234",
    "role": "creator",
    "cats": "ספורט, כדורגל",
    "city": "תל אביב",
    "handle": "@edengoal",
    "followers": "203K",
    "engagement": "4.8%",
    "price": "₪2,000-8,000",
    "bio": "כדורגל זו לא משחק ⚽",
    "status": "active",
    "joined": "19/003/2025",
    "color": "rgba(236,72,153,0.15)",
    "textColor": "#ec4899",
    "emoji": "🎬",
    "verified": true
  },
  {
    "id": 52,
    "name": "שחר ביטון",
    "email": "שחרביטון@collabo.io",
    "password": "שחר1234",
    "role": "creator",
    "cats": "ספורט, גלישה",
    "city": "תל אביב",
    "handle": "@shaharsurf",
    "followers": "87K",
    "engagement": "6.6%",
    "price": "₪900-3,500",
    "bio": "חיים על הגלים 🏄",
    "status": "active",
    "joined": "14/002/2025",
    "color": "rgba(0,207,255,0.15)",
    "textColor": "#00cfff",
    "emoji": "✨",
    "verified": false
  },
  {
    "id": 53,
    "name": "נועא קירל",
    "email": "נועאקירל@collabo.io",
    "password": "נועא1234",
    "role": "creator",
    "cats": "מוזיקה, שירה",
    "city": "תל אביב",
    "handle": "@noamusic",
    "followers": "312K",
    "engagement": "4.5%",
    "price": "₪3,500-12,000",
    "bio": "מוזיקה היא הנשמה 🎵",
    "status": "active",
    "joined": "21/005/2025",
    "color": "rgba(255,215,0,0.15)",
    "textColor": "#ffd700",
    "emoji": "🌟",
    "verified": true
  },
  {
    "id": 54,
    "name": "אסף אוחיון",
    "email": "אסףאוחיון@collabo.io",
    "password": "אסף1234",
    "role": "creator",
    "cats": "מוזיקה, DJ",
    "city": "תל אביב",
    "handle": "@asafbeats",
    "followers": "134K",
    "engagement": "5.3%",
    "price": "₪1,300-5,500",
    "bio": "מפיק ו-DJ 🎧",
    "status": "active",
    "joined": "05/005/2025",
    "color": "rgba(0,229,160,0.15)",
    "textColor": "#00e5a0",
    "emoji": "💫",
    "verified": false
  },
  {
    "id": 55,
    "name": "דינה אזולאי",
    "email": "דינהאזולאי@collabo.io",
    "password": "דינה1234",
    "role": "creator",
    "cats": "בריאות, תזונה",
    "city": "תל אביב",
    "handle": "@dinahealth",
    "followers": "96K",
    "engagement": "6.7%",
    "price": "₪1,000-4,000",
    "bio": "דיאטנית קלינית 🥗",
    "status": "active",
    "joined": "16/001/2025",
    "color": "rgba(255,77,77,0.15)",
    "textColor": "#ff4d4d",
    "emoji": "🎨",
    "verified": true
  },
  {
    "id": 56,
    "name": "יורם בן נון",
    "email": "יורםבןנון@collabo.io",
    "password": "יורם1234",
    "role": "creator",
    "cats": "בריאות, מדיטציה",
    "city": "תל אביב",
    "handle": "@yoramwellness",
    "followers": "67K",
    "engagement": "7.3%",
    "price": "₪700-2,800",
    "bio": "בריאות הנפש 🧠",
    "status": "active",
    "joined": "04/004/2025",
    "color": "rgba(245,166,35,0.15)",
    "textColor": "#f5a623",
    "emoji": "🎵",
    "verified": true
  },
  {
    "id": 57,
    "name": "ורד שמחון",
    "email": "ורדשמחון@collabo.io",
    "password": "ורד1234",
    "role": "creator",
    "cats": "הורות, ילדים",
    "city": "רעננה",
    "handle": "@veredmom",
    "followers": "145K",
    "engagement": "5.9%",
    "price": "₪1,400-5,600",
    "bio": "אמא ל4 ✨",
    "status": "active",
    "joined": "15/002/2025",
    "color": "rgba(168,85,247,0.15)",
    "textColor": "#a855f7",
    "emoji": "🏃",
    "verified": true
  },
  {
    "id": 58,
    "name": "עמרי גבע",
    "email": "עמריגבע@collabo.io",
    "password": "עמרי1234",
    "role": "creator",
    "cats": "הורות, אבות",
    "city": "כפר סבא",
    "handle": "@omridad",
    "followers": "82K",
    "engagement": "6.8%",
    "price": "₪850-3,300",
    "bio": "אבא מודרני 👨‍👧",
    "status": "active",
    "joined": "06/001/2025",
    "color": "rgba(236,72,153,0.15)",
    "textColor": "#ec4899",
    "emoji": "🧘",
    "verified": true
  },
  {
    "id": 59,
    "name": "מאיה ארט",
    "email": "מאיהארט@collabo.io",
    "password": "מאיה1234",
    "role": "creator",
    "cats": "אמנות, ציור",
    "city": "תל אביב",
    "handle": "@mayaart",
    "followers": "74K",
    "engagement": "7.9%",
    "price": "₪800-3,200",
    "bio": "צייר ואמן 🎨",
    "status": "active",
    "joined": "10/001/2025",
    "color": "rgba(0,207,255,0.15)",
    "textColor": "#00cfff",
    "emoji": "🌿",
    "verified": true
  },
  {
    "id": 60,
    "name": "בן גרפיק",
    "email": "בןגרפיק@collabo.io",
    "password": "בן1234",
    "role": "creator",
    "cats": "אמנות, גרפיקה",
    "city": "תל אביב",
    "handle": "@bengraphic",
    "followers": "59K",
    "engagement": "8.6%",
    "price": "₪650-2,600",
    "bio": "עיצוב שמספר סיפור 🖌️",
    "status": "active",
    "joined": "11/003/2025",
    "color": "rgba(255,215,0,0.15)",
    "textColor": "#ffd700",
    "emoji": "💄",
    "verified": true
  },
  {
    "id": 61,
    "name": "ניר הומור",
    "email": "נירהומור@collabo.io",
    "password": "ניר1234",
    "role": "creator",
    "cats": "קומדי, סטנדאפ",
    "city": "תל אביב",
    "handle": "@nirhumor",
    "followers": "267K",
    "engagement": "4.6%",
    "price": "₪2,800-10,000",
    "bio": "גורם לאנשים לצחוק 😂",
    "status": "active",
    "joined": "09/003/2025",
    "color": "rgba(0,229,160,0.15)",
    "textColor": "#00e5a0",
    "emoji": "👗",
    "verified": false
  },
  {
    "id": 62,
    "name": "יובל קומי",
    "email": "יובלקומי@collabo.io",
    "password": "יובל1234",
    "role": "creator",
    "cats": "קומדי, פרודיה",
    "city": "תל אביב",
    "handle": "@yuvalcomedy",
    "followers": "189K",
    "engagement": "5.1%",
    "price": "₪1,900-7,500",
    "bio": "פרודיות ויראליות 🤣",
    "status": "active",
    "joined": "14/003/2025",
    "color": "rgba(255,77,77,0.15)",
    "textColor": "#ff4d4d",
    "emoji": "🍕",
    "verified": false
  },
  {
    "id": 63,
    "name": "שיר ישראל",
    "email": "שירישראל@collabo.io",
    "password": "שיר1234",
    "role": "creator",
    "cats": "טיולים, ישראל",
    "city": "ירושלים",
    "handle": "@shirtravel_il",
    "followers": "91K",
    "engagement": "6.5%",
    "price": "₪950-3,800",
    "bio": "ישראל יפה 🇮🇱",
    "status": "active",
    "joined": "11/001/2025",
    "color": "rgba(245,166,35,0.15)",
    "textColor": "#f5a623",
    "emoji": "☕",
    "verified": true
  },
  {
    "id": 64,
    "name": "לילי דיזיין",
    "email": "לילידיזיין@collabo.io",
    "password": "לילי1234",
    "role": "creator",
    "cats": "עיצוב פנים, ריהוט",
    "city": "תל אביב",
    "handle": "@lilydesign",
    "followers": "138K",
    "engagement": "5.8%",
    "price": "₪1,350-5,400",
    "bio": "הבית הוא הביטוי שלך 🏡",
    "status": "active",
    "joined": "04/005/2025",
    "color": "rgba(168,85,247,0.15)",
    "textColor": "#a855f7",
    "emoji": "✈️",
    "verified": false
  },
  {
    "id": 65,
    "name": "גולן עיצוב",
    "email": "גולןעיצוב@collabo.io",
    "password": "גולן1234",
    "role": "creator",
    "cats": "עיצוב, ארכיטקטורה",
    "city": "הרצליה",
    "handle": "@golandesign",
    "followers": "86K",
    "engagement": "6.2%",
    "price": "₪900-3,600",
    "bio": "פחות זה יותר 🏛️",
    "status": "active",
    "joined": "15/003/2025",
    "color": "rgba(236,72,153,0.15)",
    "textColor": "#ec4899",
    "emoji": "💪",
    "verified": false
  },
  {
    "id": 66,
    "name": "ירון קפה",
    "email": "ירוןקפה@collabo.io",
    "password": "ירון1234",
    "role": "creator",
    "cats": "קפה, בריסטה",
    "city": "תל אביב",
    "handle": "@yaroncoffee",
    "followers": "72K",
    "engagement": "7.4%",
    "price": "₪750-3,000",
    "bio": "קפה כאמנות ☕",
    "status": "active",
    "joined": "01/001/2025",
    "color": "rgba(0,207,255,0.15)",
    "textColor": "#00cfff",
    "emoji": "🎮",
    "verified": true
  },
  {
    "id": 67,
    "name": "עדי גורמה",
    "email": "עדיגורמה@collabo.io",
    "password": "עדי1234",
    "role": "creator",
    "cats": "אוכל, גורמה",
    "city": "תל אביב",
    "handle": "@adigourmet",
    "followers": "104K",
    "engagement": "5.9%",
    "price": "₪1,050-4,200",
    "bio": "גסטרונומיה ישראלית 🍽️",
    "status": "active",
    "joined": "21/004/2025",
    "color": "rgba(255,215,0,0.15)",
    "textColor": "#ffd700",
    "emoji": "📚",
    "verified": true
  },
  {
    "id": 68,
    "name": "מיטל ספרים",
    "email": "מיטלספרים@collabo.io",
    "password": "מיטל1234",
    "role": "creator",
    "cats": "ספרים, תרבות",
    "city": "ירושלים",
    "handle": "@mitalbooks",
    "followers": "63K",
    "engagement": "8.7%",
    "price": "₪650-2,600",
    "bio": "ספר ביום 📚",
    "status": "active",
    "joined": "17/005/2025",
    "color": "rgba(0,229,160,0.15)",
    "textColor": "#00e5a0",
    "emoji": "🔬",
    "verified": false
  },
  {
    "id": 69,
    "name": "יניב גיימר",
    "email": "יניבגיימר@collabo.io",
    "password": "יניב1234",
    "role": "creator",
    "cats": "גיימינג, ספורט אלקטרוני",
    "city": "תל אביב",
    "handle": "@yanivgamer",
    "followers": "178K",
    "engagement": "5.3%",
    "price": "₪1,700-6,800",
    "bio": "גיימר מקצועי 🎮",
    "status": "active",
    "joined": "21/005/2025",
    "color": "rgba(255,77,77,0.15)",
    "textColor": "#ff4d4d",
    "emoji": "🚀",
    "verified": false
  },
  {
    "id": 70,
    "name": "דר עדי",
    "email": "דרעדי@collabo.io",
    "password": "דר1234",
    "role": "creator",
    "cats": "חינוך, פסיכולוגיה",
    "city": "תל אביב",
    "handle": "@dradi_edu",
    "followers": "124K",
    "engagement": "5.6%",
    "price": "₪1,200-5,000",
    "bio": "פסיכולוג ומחנך 🧑‍🏫",
    "status": "active",
    "joined": "08/003/2025",
    "color": "rgba(245,166,35,0.15)",
    "textColor": "#f5a623",
    "emoji": "📸",
    "verified": false
  },
  {
    "id": 71,
    "name": "תמר עשה זאת",
    "email": "תמרעשהזאת@collabo.io",
    "password": "תמר1234",
    "role": "creator",
    "cats": "DIY, יצירה",
    "city": "נתניה",
    "handle": "@tamardiy",
    "followers": "79K",
    "engagement": "7.1%",
    "price": "₪820-3,300",
    "bio": "עשה זאת בעצמך 🔨",
    "status": "active",
    "joined": "19/005/2025",
    "color": "rgba(168,85,247,0.15)",
    "textColor": "#a855f7",
    "emoji": "🎬",
    "verified": false
  },
  {
    "id": 72,
    "name": "ניצן חתונות",
    "email": "ניצןחתונות@collabo.io",
    "password": "ניצן1234",
    "role": "creator",
    "cats": "חתונות, אירועים",
    "city": "תל אביב",
    "handle": "@nitzanwedding",
    "followers": "168K",
    "engagement": "5.4%",
    "price": "₪1,600-6,500",
    "bio": "היום הכי יפה 💒",
    "status": "active",
    "joined": "11/001/2025",
    "color": "rgba(236,72,153,0.15)",
    "textColor": "#ec4899",
    "emoji": "✨",
    "verified": false
  },
  {
    "id": 73,
    "name": "אלכס לוקסוס",
    "email": "אלכסלוקסוס@collabo.io",
    "password": "אלכס1234",
    "role": "creator",
    "cats": "יוקרה, מלונות",
    "city": "הרצליה",
    "handle": "@alexluxury",
    "followers": "221K",
    "engagement": "4.9%",
    "price": "₪2,300-9,000",
    "bio": "חיים ברמה גבוהה ✈️",
    "status": "active",
    "joined": "17/001/2025",
    "color": "rgba(0,207,255,0.15)",
    "textColor": "#00cfff",
    "emoji": "🌟",
    "verified": false
  },
  {
    "id": 74,
    "name": "אור אקסטרים",
    "email": "אוראקסטרים@collabo.io",
    "password": "אור1234",
    "role": "creator",
    "cats": "ספורט אתגרי, טיפוס",
    "city": "חיפה",
    "handle": "@oradventure",
    "followers": "93K",
    "engagement": "6.7%",
    "price": "₪950-3,800",
    "bio": "גבולות לשבור 🧗",
    "status": "active",
    "joined": "21/002/2025",
    "color": "rgba(255,215,0,0.15)",
    "textColor": "#ffd700",
    "emoji": "💫",
    "verified": true
  },
  {
    "id": 75,
    "name": "טכנו ביתי",
    "email": "טכנוביתי@collabo.io",
    "password": "טכנו1234",
    "role": "creator",
    "cats": "טכנולוגיה, בית חכם",
    "city": "תל אביב",
    "handle": "@techno_home",
    "followers": "84K",
    "engagement": "6.1%",
    "price": "₪860-3,400",
    "bio": "הבית החכם 🏠",
    "status": "active",
    "joined": "17/004/2025",
    "color": "rgba(0,229,160,0.15)",
    "textColor": "#00e5a0",
    "emoji": "🎨",
    "verified": false
  },
  {
    "id": 76,
    "name": "דר מדע",
    "email": "דרמדע@collabo.io",
    "password": "דר1234",
    "role": "creator",
    "cats": "מדע, חינוך",
    "city": "ירושלים",
    "handle": "@drscience_il",
    "followers": "156K",
    "engagement": "5.7%",
    "price": "₪1,500-6,000",
    "bio": "מדע לכולם 🔬",
    "status": "active",
    "joined": "05/003/2025",
    "color": "rgba(255,77,77,0.15)",
    "textColor": "#ff4d4d",
    "emoji": "🎵",
    "verified": false
  },
  {
    "id": 77,
    "name": "רן מכוניות",
    "email": "רןמכוניות@collabo.io",
    "password": "רן1234",
    "role": "creator",
    "cats": "רכב, מירוצים",
    "city": "תל אביב",
    "handle": "@rancars",
    "followers": "147K",
    "engagement": "5.4%",
    "price": "₪1,400-5,800",
    "bio": "אוהב מכוניות 🚗",
    "status": "active",
    "joined": "22/002/2025",
    "color": "rgba(245,166,35,0.15)",
    "textColor": "#f5a623",
    "emoji": "🏃",
    "verified": false
  },
  {
    "id": 78,
    "name": "עמית פודקאסט",
    "email": "עמיתפודקאסט@collabo.io",
    "password": "עמית1234",
    "role": "creator",
    "cats": "פודקאסט, עסקים",
    "city": "תל אביב",
    "handle": "@amitpodcast",
    "followers": "98K",
    "engagement": "6.4%",
    "price": "₪1,000-4,100",
    "bio": "שיחות שמשנות 🎙️",
    "status": "active",
    "joined": "24/001/2025",
    "color": "rgba(168,85,247,0.15)",
    "textColor": "#a855f7",
    "emoji": "🧘",
    "verified": false
  },
  {
    "id": 79,
    "name": "ים ושמש",
    "email": "יםושמש@collabo.io",
    "password": "ים1234",
    "role": "creator",
    "cats": "ים, ספורט ים",
    "city": "תל אביב",
    "handle": "@seaandsun_il",
    "followers": "118K",
    "engagement": "5.8%",
    "price": "₪1,150-4,600",
    "bio": "חיים על החוף 🌊",
    "status": "active",
    "joined": "07/005/2025",
    "color": "rgba(236,72,153,0.15)",
    "textColor": "#ec4899",
    "emoji": "🌿",
    "verified": false
  },
  {
    "id": 80,
    "name": "סטארטאפ ישראל",
    "email": "סטארטאפישראל@collabo.io",
    "password": "סטארטאפ1234",
    "role": "creator",
    "cats": "עסקים, יזמות",
    "city": "תל אביב",
    "handle": "@startup_il",
    "followers": "187K",
    "engagement": "5.2%",
    "price": "₪1,850-7,500",
    "bio": "עולם הסטארטאפ 🚀",
    "status": "active",
    "joined": "19/004/2025",
    "color": "rgba(0,207,255,0.15)",
    "textColor": "#00cfff",
    "emoji": "💄",
    "verified": true
  },
  {
    "id": 81,
    "name": "עולם הילד",
    "email": "עולםהילד@collabo.io",
    "password": "עולם1234",
    "role": "creator",
    "cats": "ילדים, צעצועים",
    "city": "רמת גן",
    "handle": "@kidworld_il",
    "followers": "94K",
    "engagement": "6.9%",
    "price": "₪960-3,800",
    "bio": "כל מה שלילדים 👶",
    "status": "active",
    "joined": "22/003/2025",
    "color": "rgba(255,215,0,0.15)",
    "textColor": "#ffd700",
    "emoji": "👗",
    "verified": true
  },
  {
    "id": 82,
    "name": "פיט גרלז",
    "email": "פיטגרלז@collabo.io",
    "password": "פיט1234",
    "role": "creator",
    "cats": "כושר, נשים",
    "city": "תל אביב",
    "handle": "@fitgirlz_il",
    "followers": "163K",
    "engagement": "5.5%",
    "price": "₪1,600-6,300",
    "bio": "כושר לנשים 💪",
    "status": "active",
    "joined": "20/001/2025",
    "color": "rgba(0,229,160,0.15)",
    "textColor": "#00e5a0",
    "emoji": "🍕",
    "verified": true
  },
  {
    "id": 83,
    "name": "רועי ריצות",
    "email": "רועיריצות@collabo.io",
    "password": "רועי1234",
    "role": "creator",
    "cats": "ריצה, מרתון, כושר",
    "city": "תל אביב",
    "handle": "@roirunning",
    "followers": "54K",
    "engagement": "8.2%",
    "price": "₪580-2,300",
    "bio": "ריצה שמשנה חיים 🏃",
    "status": "active",
    "joined": "04/005/2025",
    "color": "rgba(255,77,77,0.15)",
    "textColor": "#ff4d4d",
    "emoji": "☕",
    "verified": false
  },
  {
    "id": 84,
    "name": "לי צמחוני",
    "email": "ליצמחוני@collabo.io",
    "password": "לי1234",
    "role": "creator",
    "cats": "טבעוני, מתכונים",
    "city": "תל אביב",
    "handle": "@leivegan",
    "followers": "76K",
    "engagement": "7.6%",
    "price": "₪780-3,100",
    "bio": "טבעוני ומאושר 🥑",
    "status": "active",
    "joined": "01/004/2025",
    "color": "rgba(245,166,35,0.15)",
    "textColor": "#f5a623",
    "emoji": "✈️",
    "verified": true
  },
  {
    "id": 85,
    "name": "אדם צילום",
    "email": "אדםצילום@collabo.io",
    "password": "אדם1234",
    "role": "creator",
    "cats": "צילום, פורטרט",
    "city": "תל אביב",
    "handle": "@adamphoto",
    "followers": "108K",
    "engagement": "6.0%",
    "price": "₪1,080-4,300",
    "bio": "צלם שמספר סיפורים 📷",
    "status": "active",
    "joined": "09/003/2025",
    "color": "rgba(168,85,247,0.15)",
    "textColor": "#a855f7",
    "emoji": "💪",
    "verified": true
  },
  {
    "id": 86,
    "name": "נגה מוזיקה",
    "email": "נגהמוזיקה@collabo.io",
    "password": "נגה1234",
    "role": "creator",
    "cats": "מוזיקה, ריקוד",
    "city": "תל אביב",
    "handle": "@nogamusic",
    "followers": "142K",
    "engagement": "5.4%",
    "price": "₪1,400-5,600",
    "bio": "מוזיקה וריקוד 💃",
    "status": "active",
    "joined": "08/003/2025",
    "color": "rgba(236,72,153,0.15)",
    "textColor": "#ec4899",
    "emoji": "🎮",
    "verified": true
  },
  {
    "id": 87,
    "name": "יהל טבע",
    "email": "יהלטבע@collabo.io",
    "password": "יהל1234",
    "role": "creator",
    "cats": "טבע, אקולוגיה",
    "city": "הרצליה",
    "handle": "@yahelnature",
    "followers": "69K",
    "engagement": "7.2%",
    "price": "₪710-2,800",
    "bio": "שומר הטבע 🌳",
    "status": "active",
    "joined": "17/005/2025",
    "color": "rgba(0,207,255,0.15)",
    "textColor": "#00cfff",
    "emoji": "📚",
    "verified": true
  },
  {
    "id": 100,
    "name": "קפה נמרוד",
    "email": "קפהנמרוד@collabo.io",
    "password": "קפה1234",
    "role": "business",
    "cats": "קפה",
    "city": "תל אביב",
    "budget": "₪5,000-15,000",
    "status": "active",
    "joined": "25/005/2025",
    "color": "rgba(0,229,160,0.15)",
    "textColor": "#00e5a0",
    "emoji": "🏢",
    "verified": true
  },
  {
    "id": 101,
    "name": "פיצה רומא",
    "email": "פיצהרומא@collabo.io",
    "password": "פיצה1234",
    "role": "business",
    "cats": "מסעדה ואוכל",
    "city": "תל אביב",
    "budget": "₪8,000-20,000",
    "status": "active",
    "joined": "23/003/2025",
    "color": "rgba(255,77,77,0.15)",
    "textColor": "#ff4d4d",
    "emoji": "🍕",
    "verified": true
  },
  {
    "id": 102,
    "name": "גימנסיה פרו",
    "email": "גימנסיהפרו@collabo.io",
    "password": "גימנסיה1234",
    "role": "business",
    "cats": "חדר כושר",
    "city": "הרצליה",
    "budget": "₪6,000-18,000",
    "status": "active",
    "joined": "18/002/2025",
    "color": "rgba(245,166,35,0.15)",
    "textColor": "#f5a623",
    "emoji": "☕",
    "verified": true
  },
  {
    "id": 103,
    "name": "ביוטי סטור",
    "email": "ביוטיסטור@collabo.io",
    "password": "ביוטי1234",
    "role": "business",
    "cats": "יופי וקוסמטיקה",
    "city": "תל אביב",
    "budget": "₪10,000-30,000",
    "status": "active",
    "joined": "05/004/2025",
    "color": "rgba(168,85,247,0.15)",
    "textColor": "#a855f7",
    "emoji": "💪",
    "verified": true
  },
  {
    "id": 104,
    "name": "פאשן אאוטלט",
    "email": "פאשןאאוטלט@collabo.io",
    "password": "פאשן1234",
    "role": "business",
    "cats": "אופנה",
    "city": "תל אביב",
    "budget": "₪12,000-40,000",
    "status": "active",
    "joined": "22/004/2025",
    "color": "rgba(236,72,153,0.15)",
    "textColor": "#ec4899",
    "emoji": "💄",
    "verified": true
  },
  {
    "id": 105,
    "name": "טק גאדג'טס",
    "email": "טקגאדגטס@collabo.io",
    "password": "טק1234",
    "role": "business",
    "cats": "טכנולוגיה",
    "city": "תל אביב",
    "budget": "₪7,000-22,000",
    "status": "active",
    "joined": "08/003/2025",
    "color": "rgba(0,207,255,0.15)",
    "textColor": "#00cfff",
    "emoji": "👗",
    "verified": true
  },
  {
    "id": 106,
    "name": "ספא דלוקס",
    "email": "ספאדלוקס@collabo.io",
    "password": "ספא1234",
    "role": "business",
    "cats": "בריאות",
    "city": "הרצליה",
    "budget": "₪9,000-25,000",
    "status": "active",
    "joined": "16/003/2025",
    "color": "rgba(255,215,0,0.15)",
    "textColor": "#ffd700",
    "emoji": "🏨",
    "verified": true
  },
  {
    "id": 107,
    "name": "מלון בוטיק",
    "email": "מלוןבוטיק@collabo.io",
    "password": "מלון1234",
    "role": "business",
    "cats": "מלון ואירוח",
    "city": "תל אביב",
    "budget": "₪15,000-50,000",
    "status": "active",
    "joined": "23/002/2025",
    "color": "rgba(0,229,160,0.15)",
    "textColor": "#00e5a0",
    "emoji": "🥗",
    "verified": true
  },
  {
    "id": 108,
    "name": "סופרפוד",
    "email": "סופרפוד@collabo.io",
    "password": "סופרפוד1234",
    "role": "business",
    "cats": "מסעדה ואוכל",
    "city": "תל אביב",
    "budget": "₪5,500-16,000",
    "status": "active",
    "joined": "25/001/2025",
    "color": "rgba(255,77,77,0.15)",
    "textColor": "#ff4d4d",
    "emoji": "🛍️",
    "verified": true
  },
  {
    "id": 109,
    "name": "ספורט פלוס",
    "email": "ספורטפלוס@collabo.io",
    "password": "ספורט1234",
    "role": "business",
    "cats": "חדר כושר",
    "city": "ראשון לציון",
    "budget": "₪4,000-12,000",
    "status": "active",
    "joined": "12/002/2025",
    "color": "rgba(245,166,35,0.15)",
    "textColor": "#f5a623",
    "emoji": "🚗",
    "verified": true
  },
  {
    "id": 110,
    "name": "עיצוב הבית",
    "email": "עיצובהבית@collabo.io",
    "password": "עיצוב1234",
    "role": "business",
    "cats": "ריטייל",
    "city": "תל אביב",
    "budget": "₪8,000-24,000",
    "status": "active",
    "joined": "02/001/2025",
    "color": "rgba(168,85,247,0.15)",
    "textColor": "#a855f7",
    "emoji": "🧖",
    "verified": true
  },
  {
    "id": 111,
    "name": "אורגני מרקט",
    "email": "אורגנימרקט@collabo.io",
    "password": "אורגני1234",
    "role": "business",
    "cats": "מסעדה ואוכל",
    "city": "תל אביב",
    "budget": "₪6,000-18,000",
    "status": "active",
    "joined": "26/003/2025",
    "color": "rgba(236,72,153,0.15)",
    "textColor": "#ec4899",
    "emoji": "🍣",
    "verified": true
  },
  {
    "id": 112,
    "name": "קידס פאן",
    "email": "קידספאן@collabo.io",
    "password": "קידס1234",
    "role": "business",
    "cats": "ריטייל",
    "city": "פתח תקווה",
    "budget": "₪5,000-15,000",
    "status": "active",
    "joined": "28/003/2025",
    "color": "rgba(0,207,255,0.15)",
    "textColor": "#00cfff",
    "emoji": "🐾",
    "verified": true
  },
  {
    "id": 113,
    "name": "וינו בר",
    "email": "וינובר@collabo.io",
    "password": "וינו1234",
    "role": "business",
    "cats": "מסעדה ואוכל",
    "city": "תל אביב",
    "budget": "₪7,000-20,000",
    "status": "active",
    "joined": "07/001/2025",
    "color": "rgba(255,215,0,0.15)",
    "textColor": "#ffd700",
    "emoji": "🍷",
    "verified": true
  },
  {
    "id": 114,
    "name": "רנט א קאר",
    "email": "רנטאקאר@collabo.io",
    "password": "רנט1234",
    "role": "business",
    "cats": "אחר",
    "city": "תל אביב",
    "budget": "₪9,000-28,000",
    "status": "active",
    "joined": "02/003/2025",
    "color": "rgba(0,229,160,0.15)",
    "textColor": "#00e5a0",
    "emoji": "🦷",
    "verified": true
  },
  {
    "id": 115,
    "name": "דנטל קליניק",
    "email": "דנטלקליניק@collabo.io",
    "password": "דנטל1234",
    "role": "business",
    "cats": "בריאות",
    "city": "הרצליה",
    "budget": "₪5,000-14,000",
    "status": "active",
    "joined": "28/002/2025",
    "color": "rgba(255,77,77,0.15)",
    "textColor": "#ff4d4d",
    "emoji": "🏢",
    "verified": true
  },
  {
    "id": 116,
    "name": "פט שופ",
    "email": "פטשופ@collabo.io",
    "password": "פט1234",
    "role": "business",
    "cats": "ריטייל",
    "city": "תל אביב",
    "budget": "₪4,500-13,000",
    "status": "active",
    "joined": "20/003/2025",
    "color": "rgba(245,166,35,0.15)",
    "textColor": "#f5a623",
    "emoji": "🍕",
    "verified": true
  },
  {
    "id": 117,
    "name": "סושי בר",
    "email": "סושיבר@collabo.io",
    "password": "סושי1234",
    "role": "business",
    "cats": "מסעדה ואוכל",
    "city": "תל אביב",
    "budget": "₪6,500-19,000",
    "status": "active",
    "joined": "01/005/2025",
    "color": "rgba(168,85,247,0.15)",
    "textColor": "#a855f7",
    "emoji": "☕",
    "verified": true
  },
  {
    "id": 118,
    "name": "יוגה סטודיו",
    "email": "יוגהסטודיו@collabo.io",
    "password": "יוגה1234",
    "role": "business",
    "cats": "חדר כושר",
    "city": "תל אביב",
    "budget": "₪3,500-10,000",
    "status": "active",
    "joined": "27/001/2025",
    "color": "rgba(236,72,153,0.15)",
    "textColor": "#ec4899",
    "emoji": "💪",
    "verified": true
  },
  {
    "id": 119,
    "name": "ברבר שופ",
    "email": "ברברשופ@collabo.io",
    "password": "ברבר1234",
    "role": "business",
    "cats": "יופי וקוסמטיקה",
    "city": "תל אביב",
    "budget": "₪4,000-12,000",
    "status": "active",
    "joined": "25/001/2025",
    "color": "rgba(0,207,255,0.15)",
    "textColor": "#00cfff",
    "emoji": "💄",
    "verified": true
  }
];

let EXTRA_USERS = [];

export default function handler(req, res) {
  res.setHeader('Access-Control-Allow-Origin', '*');
  res.setHeader('Access-Control-Allow-Methods', 'POST,OPTIONS');
  res.setHeader('Access-Control-Allow-Headers', 'Content-Type');
  if (req.method === 'OPTIONS') { res.status(204).end(); return; }

  const email = (req.body?.email || '').trim().toLowerCase();
  const password = req.body?.password || '';
  const allUsers = [...DEMO_USERS, ...EXTRA_USERS];
  const user = allUsers.find(u => u.email.toLowerCase() === email);

  if (!user) return res.json({ ok: false, error: 'משתמש לא קיים — הרשם קודם' });
  if (user.password !== password) return res.json({ ok: false, error: 'סיסמה שגויה' });
  res.json({ ok: true, user });
}
